### ISSUE TITLE
Stop scraping emails illegaly from GitHub for spam

### ISSUE THREAD

**Issue by Trojaner** [dubverse-ai/MahaTTS#16]
![image](https://github.com/dubverse-ai/MahaTTS/assets/1809172/a1cebeec-d699-438d-b0cf-25295f91a2eb)

This is a clear violation of the [GitHub Terms of Services](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) and possibly violates local data protection laws like the GDPR.

DO NOT MASS EMAIL STARGAZERS OF GITHUB REPOSITORIES.

**Comment by pursuitcurves** [comment]
Apologies on behalf of the team. We’ll stop the emails.

**Comment by servel333** [comment]
This is still happening.
