### ISSUE TITLE
Spam emails

### ISSUE THREAD

**Issue by servel333** [dubverse-ai/MahaTTS#18]
These emails continue to come. It's clear your team has no intention to stop collecting emails and sending out this garbage.

So all I can say is, shame on you and your whole team.

**Comment by pursuitcurves** [comment]
Hi servel, we did not send any emails in the last 10 or so odd days.

**Comment by servel333** [comment]
I received the email right before posting this, so you are either lying, or severely mistaken. Either way, it doesn't show a good faith effort to stop.
